# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  private_lane :run_gradle_from_root do |options|
    sh("cd .. && ./gradlew --no-daemon #{options[:task]}")
  end

  desc "Runs spotless formatting validation and detekt static analysis"
  lane :lint do
    run_gradle_from_root(task: "spotlessCheck detekt")
  end

  desc "Runs all the tests for all variants"
  lane :test do
    run_gradle_from_root(task: "test")
  end

  desc "Verifies JaCoCo coverage for all modules configured with the coverage plugin"
  lane :coverage do
    run_gradle_from_root(task: "jacocoTestCoverageVerification")
  end

  desc "Assemble main outputs for all the variants"
  lane :assemble do
    run_gradle_from_root(task: "assemble")
  end

  desc "Runs the main CI quality gates in order"
  lane :ci do
    lint
    test
    coverage
    assemble
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
