name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  assemble_and_test:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify Java version
        run: java -version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Ruby gems
        run: bundle install --jobs 4 --retry 3

      - name: Run build with Fastlane
        run: bundle exec fastlane assemble

      - name: Run tests with Fastlane
        run: bundle exec fastlane test
